### PR TITLE
simplify README

### PR DESCRIPTION
**Pull request by IndrajeetPatil**

### CODE REVIEW

**Comment by IndrajeetPatil** [comment]
For `README`/markdown files, I don't have a strong preference. But I often use `styler` to style documents, which automatically adopts the 80-characters-per-line convention. And I don't mind it.

> I usually like to use one-sentence-per-line because it makes the version history cleaner.

I am curious. Why will this be cleaner than 80-characters-per-line?

**Comment by mattansb** [comment]
Because changes don't shift whole lines/paragraphs... :(

**Comment by IndrajeetPatil** [comment]
No, I mean if all the markdown documents are _already_ at 80-width to begin with, and then I make a change, will that be easier to notice in version history than one-sentence-per-line approach?

**Comment by IndrajeetPatil** [comment]
Put another way, now that the README is in 80-width, will all future edits to its content be easier to read/review in version history than one-sentence-per-line approach or more difficult?

This is what always confuses me when we discuss this issue. I agree that the commit that converts one-sentence-per-line approach to 80-width one looks like a huge change, when it is not. But that's not what you are saying, right?

If I understand you correctly, you are saying that reviewing changes **in general** is much easier with one-sentence-per-line approach than with 80-characters-per-line approach?

**Comment by bwiernik** [comment]
I mean this:

We should make one big commit to restructure. That will be ugly. But, all future commits will then never be cluttered up with line refactoring. 

Otherwise, any future edits are likely to invoice extraneous line edits to preserve the 80 chars. 

Especially here where it was changed from sentence to 80-char, I think that's a refactor in the wrong direction.

**Pull request merged**
