### PR TITLE
Add model info to dashboard

### LINKED ISSUE #214: Use GitHub actions to check all reverse dependencies of our packages
Doing this is quite resource intensive on local machines and isn't going to scale well, especially as our reverse dependencies continue to grow.

A good place to start would be this repo and adapting it to our needs:
https://github.com/yihui/crandalf

### PR DESCRIPTION
**Pull request by IndrajeetPatil**
Closes #214

@strengejacke WDYT?

https://user-images.githubusercontent.com/11330453/185802420-5678aab3-1a86-455c-bb28-2d88e5a8da8d.mov

### CODE REVIEW

**Comment by strengejacke** [comment]
nice! good idea!

**Review by strengejacke — APPROVED** [review]

**Comment by IndrajeetPatil** [comment]
@strengejacke Should we convert the other data frames to DataTables as well? 

I think they look prettier, and it's much nicer to work with them.

**Comment by strengejacke** [comment]
The data frames are not formatted then and not shown as "table" (like formatted CI or so).

**Comment by IndrajeetPatil** [comment]
Ah, yes, that's true.

Forgot that we have some custom formatting here. Okay, then we can just stick to what we currently have.

**Pull request merged**
