### PR TITLE
Version policy: support the previous 5 versions

### LINKED ISSUE #401: Discussion: Bump minimum needed R version to `R 4.0` across the ecosystem?
I think this will be a good idea for a few reasons:

- It has been 5 years since `R 3.6` came out (2019-04-26); that's enough time for people to have upgraded to a newer R version.

- An increasing number of dependencies are using the base pipe (introduced in `R 4.0`), which means the new versions of dependencies can't even be installed on `R 3.6`. If you haven't noticed that, it's because I have been [carving out exceptions](https://github.com/easystats/workflows/blob/0f4346b7573dab70638752cab2c454b63476e3db/.github/workflows/R-CMD-check.yaml#L135) for them in the workflows.

- Very few of our test suites pass on `R 3.6` (e.g. [datawizard fails](https://github.com/easystats/datawizard/issues/500)), and some don't even run (e.g. _see_ because the graphics engine for `R 3.6` is not supported by _vdiffr_).

- It's [holding us back from using the base pipe](https://github.com/easystats/modelbased/pull/252), which now both us (as developers) and the users have got used to using.

All of this combined makes it quite a hurdle to keep supporting this R version. Even the tidyverse [no longer supports it](https://www.tidyverse.org/blog/2019/04/r-version-support/):

image

### PR DESCRIPTION
**Pull request by etiennebacher**
Close #401

### CODE REVIEW

**Comment by IndrajeetPatil** [comment]
`{correlation}` already requires `R 4.1`, which was supposed to happen in 2026:
https://cran.r-project.org/web/packages/correlation/index.html

I don't know if that requires us to revise this policy.

**Comment by IndrajeetPatil** [comment]
I am surprised you were so cavalier about it when you pushed back so hard against [the proposal](https://github.com/easystats/easystats/issues/401) to bump the R version even to R 4.0, forget about R 4.1.

**Comment by strengejacke** [comment]
I'm not the maintainer of that package ;-)
And meanwhile, I think that since we have older package versions available for older R releases, users that can't switch just have to use the older package versions. Not perfect, but...

**Comment by bwiernik** [comment]
I've re-submitted correlation with >= 3.6 and the NOTE triggering and asked CRAN to approve anyway. Will see what they respond

**Comment by strengejacke** [comment]
> and generally he hates pipes I've learned

😆 

There are worse things in the world than depending on R 4.1...

**Comment by DominiqueMakowski** [comment]
> and generally he hates pipes I've learned

interesting! wonder why

**Comment by bwiernik** [comment]
> From my point of view, pipes should never be used in R as a pipe is a misconception for a functional language. It comes from shells. So one could simply replace this by regular function calls.

**Comment by etiennebacher** [comment]
This R-devel thread might indicate a way to keep using pipes in examples while depending on R >= 4.0.0: https://hypatia.math.ethz.ch/pipermail/r-devel/2025-March/083871.html

**Comment by bwiernik** [comment]
> This R-devel thread might indicate a way to keep using pipes in examples while depending on R >= 4.0.0: https://hypatia.math.ethz.ch/pipermail/r-devel/2025-March/083871.html

Thanks for pointing this out. Will see if I can get it to work

**Pull request merged**
